### ISSUE TITLE
Are you updating this theme?

### ISSUE THREAD

**Issue by Defman21** [xyl0n/iris-light#52]
I've seen some commits pushed to Iris, but in this repo there's nothing new from May'15. Would you update this theme?

**Comment by xyl0n** [comment]
Right now I'm considering dropping this theme, especially because I'll have little time in the next few months. However, Gtk 3.20 has been released and if I can I'll attempt to update this theme for that sometime in the summer.

**Comment by Defman21** [comment]
Sad to hear that. Thanks for the answer anyway. 👍
